name: Testing

on:
  push:
  pull_request:

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    name: Code coverage
    if: vars.CODECOV_ENABLED == 'true' || github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload coverage report to Codecov
        run: echo "Token code - $CODECOV_TOKEN"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
